name: ci-onyvore

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/**/onyvore/**'
      - 'libs/isomorphic/onyvore/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm ci --legacy-peer-deps

      - run: npx nx build app-vscode-onyvore
